# Generated by Django 5.2 on 2025-04-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_parameter_productinfo_productparameter_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
